# Generated by Django 3.1.3 on 2020-11-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snipper',
            new_name='Snippet',
        ),
    ]
